console.log('Hey, this is a story I hate');
console.log('And telling it might make me break');
console.log("But I'll tell it anyway");
console.log('How you said there was nobody else');
console.log('Then you got up and went to her house');
console.log('You guys always left me out');
console.log('');
console.log('I still have the letter you wrote');
console.log('When you told me that I was the only girl');
console.log("You'd ever want in your life");
console.log('I guess my friends were right');
console.log('');
console.log('Each day goes by and each night, I cry');
console.log('Somebody saw you with her last night');
console.log('You gave me your word, "Don\'t worry \'bout her\"');
console.log('You might love her now, but you loved me first');
console.log("Said you'd never hurt me, but here we are");
console.log('Oh, you swore on every star');
console.log('How could you be so reckless with my heart?');
console.log('');
console.log('You check in and out');
console.log('Of my heart like a hotel');
console.log('And she must be perfect, oh well');
console.log('I hope you both go to hell');
console.log('');
console.log('I still have the letter you wrote');
console.log('When you told me that I was the only girl');
console.log("You'd ever want in your life");
console.log("I guess my friends were right");
console.log('');
console.log("Each day goes by and each night, I cry");
console.log("Somebody saw you with her last night");
console.log('You gave me your word, "Don\'t worry \'bout her"');
console.log('You might love her now, but you loved me first');
console.log("Said you'd never hurt me, but here we are (here we are)");
console.log('Oh, you swore on every star');
console.log('How could you be so reckless with my heart? (Heart)');
console.log('');
console.log('How could you be so reckless?');
console.log('How could you be so reckless?');
console.log('How could you be so reckless with someone\'s heart?');
console.log('');
console.log('Hey, this is a story I hate');
console.log('But I told it to cope with the pain');
console.log('I\'m so sorry if you can relate');